name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
        working-directory: freered_app
      - name: Build APK Release
        run: flutter build apk --release
        working-directory: freered_app
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: freered_app/build/app/outputs/flutter-apk/app-release.apk
